---

- name: Generate env variable file
  template:
    src: "env.j2"
    dest: "{{ ale_path }}/.env"

- name: Install depends use native package managers
  import_tasks: native.yml
  when: not ale_use_docker

- name: Install depends use Dockerized package managers
  import_tasks: docker.yml
  when: ale_use_docker

- name: Set up permissions
  become: yes
  file:
    path: "{{ ale_path }}/{{ item }}"
    recurse: yes
    mode: 0775
  with_items:
    - vendor
    - storage
    - bootstrap/cache
  when: ale_files.setup

- name: Set up owner and group
  become: yes
  file:
    path: "{{ ale_path }}"
    recurse: yes
    owner: "{{ ale_files.owner }}"
    group: "{{ ale_files.group }}"
  when: ale_files.setup
