---

- name: Native | Ensure composer is installed
  package: name=composer state=installed
  when: not ale_skip_checks

- name: Native | Ensure npm is installed
  include_role: name=geerlingguy.nodejs
  when:
    - ale_npm.install_packages
    - not ale_skip_checks

- name: Native | Install npm packages
  shell: npm install
  #npm: path="{{ ale_path }}" state=present production={{ ale_env.APP_ENV == 'production' and ale_npm.install_prod_depends }}
  when: ale_npm.install_packages
  args:
    chdir: "{{ ale_path }}"

- name: Native | Install composer packages
  composer:
    command: install
    working_dir: "{{ ale_path }}"
    optimize_autoloader: "{{ ale_env.APP_ENV == 'production' }}"
    no_dev: "{{ ale_env.APP_ENV == 'production' }}"
    ignore_platform_reqs: yes

- name: Native | Build assets
  shell: npm run production
  when: ale_npm.install_packages and ale_npm.build
  args:
    chdir: "{{ ale_path }}"
